Part 1: Theoretical Questions

1.What are the different data structures used in Tensorflow?. Give some examples
How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example?

2.Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

Ans(1)

TensorFlow, a popular open-source machine learning library developed by the Google Brain team, various data structures are used to represent and manipulate data. Some of the key data structures include:

Tensor:
A tensor is a multi-dimensional array, a fundamental building block of TensorFlow.
Examples: Scalars (0-D tensors), Vectors (1-D tensors), Matrices (2-D tensors), and higher-dimensional tensors.

Constant:

A constant is a type of tensor whose value cannot be changed after it is defined.Example-constant_tensor = tf.constant([1, 2, 3])

Variable:

A variable is a type of tensor that can be modified after it is defined. It is often used to represent model parameters that need to be trained.
Example-variable_tensor = tf.Variable(initial_value)

Ans(2)

Matrix Addition:

Matrix addition is a simple operation where corresponding elements of two matrices are added together. The matrices involved in addition must have the same dimensions.

Example-
matrix_a = ([[1, 2], [3, 4])
matrix_b = ([[5, 6], [7, 8])
Perform matrix addition
result_matrix =([6,8],[10,12])

Matrix Multiplication:

Matrix multiplication involves multiplying corresponding elements of rows and columns in two matrices. The number of columns in the first matrix must be equal to the number of rows in the second matrix.

Example-
matrix_a=([1,2],[3,4])
matrix_b=([5,6],[7,8])
Perform matrix multiplication:
result_matrix=([19,22],[43,50])

Element-wise Operations:

Element-wise operations involve applying an operation to each corresponding element of two matrices.

Example-
matrix_a=([1,2],[3,4])
matrix_b=([5,6],[7,8])
Perform matrix multiplication element-wise:
result_matrix=([6,8],[10,12])






Part 2: Practical Implementations

Task 1: Creating and Manipulating Matrice

1.Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A

2.Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

3.Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C

4.Perform matrix addition between matrix A and matrix B, and store the result in matrix D

5.Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

#Ans(1)

In [15]:
import tensorflow as tf

# Create a 3x3 matrix with random values from a normal distribution
matrix_A = tf.random.normal(shape=(3, 3), mean=0.0, stddev=1.0)

# Display the values of matrix A
print(matrix_A.numpy())


[[ 1.0553259  -0.35126728  0.55783314]
 [ 0.5571943  -1.2428772   0.11134844]
 [-0.50066704  0.07111813 -0.86142576]]


#Ans(2)

In [8]:
# Creating a 4X4 matrix with random truncated_normal distibution
matrix_B=tf.random.truncated_normal(shape=[4,4],mean=0.0,stddev=1.0)
#Display the values of matrix B
print(matrix_B.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.7128786 ,  0.21889278, -0.34138045,  0.6173753 ],
       [ 1.0106869 , -0.5114497 , -0.21883895, -0.4079713 ],
       [-0.619567  ,  0.1735674 ,  0.44908836, -0.19726436],
       [-1.1837401 , -0.64588374, -0.37868172,  0.78289515]],
      dtype=float32)>>


#Ans(3)


In [14]:
# Create a 2X2 matrix with random values from a normal distribution with mean=3 and std=0.5
matrix_C = tf.random.normal(shape=(2, 2), mean=3.0, stddev=0.5 )

# Display the values of matrix C
print(matrix_C.numpy())

[[3.0706797 2.811026 ]
 [2.7319922 2.8728423]]


#Ans(4)

In [23]:
# Adding Matrix_A and Matrix_B
matrix_D=tf.add(matrix_A,matrix_B)
#printing matrix_D
print(matrix_D.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>>


#Ans(5)

In [26]:
# multiply MAtrix_C and Matrix_D
matrix_D=tf.cast(matrix_D,dtype=tf.float32)
matrix_E=tf.matmul(matrix_C,matrix_D)
#printing matrix_E
print(matrix_E.numpy)


<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[46.53434 , 58.297752],
       [45.120377, 56.330044]], dtype=float32)>>


Task 2: Performing Additional Matrix Operations

1.Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function

2.Calculate the transpose of matrix F and store the result in matrix G

3.Calculate the element-wise exponential of matrix F and store the result in matrix H

4.Create a matrix I by concatenating matrix F and matrix G horizontally

5.Create a matrix J by concatenating matrix F and matrix H vertically.

#Ans(1)

In [44]:
import tensorflow as tf

# Create a 3x3 matrix with random values from a normal distribution
matrix_F = tf.random.uniform(shape=(3,3))

# Display the values of matrix F
print(matrix_F.numpy())

[[0.3211447  0.5981405  0.65649116]
 [0.7640196  0.05673623 0.04946899]
 [0.08851409 0.519922   0.9530071 ]]


#Ans(2)

In [45]:
# doing transopse of matrix_F
matrix_G=tf.transpose(matrix_F)
#printing the transpose
print(matrix_G.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.3211447 , 0.7640196 , 0.08851409],
       [0.5981405 , 0.05673623, 0.519922  ],
       [0.65649116, 0.04946899, 0.9530071 ]], dtype=float32)>>


#Ans(3)

In [46]:
# Calculating Element-wise exponent of matrix F
matrix_H=tf.exp(matrix_F)
#printing the result
print(matrix_H.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.378705 , 1.8187337, 1.9280154],
       [2.1468885, 1.0583766, 1.0507131],
       [1.0925497, 1.6818964, 2.5934968]], dtype=float32)>>


#Ans(4)

In [47]:
# Matrix concatination of matrix_F and matrix_G horizantly
matrix_I=tf.concat([matrix_F,matrix_G],axis=1)
#printing result
print(matrix_I.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0.3211447 , 0.5981405 , 0.65649116, 0.3211447 , 0.7640196 ,
        0.08851409],
       [0.7640196 , 0.05673623, 0.04946899, 0.5981405 , 0.05673623,
        0.519922  ],
       [0.08851409, 0.519922  , 0.9530071 , 0.65649116, 0.04946899,
        0.9530071 ]], dtype=float32)>>


#Ans(5)

In [48]:
# Matrix concatination of matrix_F and matrix_G vertically
matrix_J=tf.concat([matrix_F,matrix_G],axis=0)
#printing result
print(matrix_J.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[0.3211447 , 0.5981405 , 0.65649116],
       [0.7640196 , 0.05673623, 0.04946899],
       [0.08851409, 0.519922  , 0.9530071 ],
       [0.3211447 , 0.7640196 , 0.08851409],
       [0.5981405 , 0.05673623, 0.519922  ],
       [0.65649116, 0.04946899, 0.9530071 ]], dtype=float32)>>
